spring:
  # Mail Configuration for Development
  mail:
    host: localhost
    port: 1025
    username: test@example.com
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

# App-specific email configuration
app:
  email:
    enabled: false  # Disable email sending in development
    from: noreply@ecommerce-dev.com

  # SMS Configuration for Development
  sms:
    enabled: false  # Disable SMS sending in development
    provider:
      url: ""  # Empty URL will trigger mock SMS service
      api-key: "dev-api-key"
    from-number: "+1234567890"
